### PR TITLE
LBAC-31 Correcting usage of assertEquals

### PR DESCRIPTION
**Pull request by Bisht13**
## Description of what I changed

I have corrected the usage of assertEquals to match its format with the conventional one. 
I have also made changes according to [this PR](https://github.com/openmrs/openmrs-module-locationbasedaccess/pull/53) so that there is no conflict while merging.

## Issue I worked on

see https://issues.openmrs.org/browse/LBAC-31

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**

- [x] My IDE is configured to follow the [**code style**]

- [x] I have **added tests** to cover my changes. 

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by anuar2k** [comment]
Happy to see that you've took into account my comment on #50 😀 at first I thought that you've decided to not correct it at all 😄

**Comment by Bisht13** [comment]
> Happy to see that you've took into account my comment on #50  at first I thought that you've decided to not correct it at all
Yup 😃. All the tests had to be changed, and I guess yes it'll help the programmer to figure out more easily if there is any assertion error.

**Comment by anuar2k** [comment]
> 
> 
> > Happy to see that you've took into account my comment on #50  at first I thought that you've decided to not correct it at all
> 
> Yup 😃. All the tests had to be changed, and I guess yes it'll help the programmer to figure out more easily if there is any assertion error.

It's really about assertion error messaged displayed to the console - this is the first thing you look for when a test breaks :P

**Comment by Bisht13** [comment]
> > > Happy to see that you've took into account my comment on #50  at first I thought that you've decided to not correct it at all
> > 
> > 
> > Yup smiley. All the tests had to be changed, and I guess yes it'll help the programmer to figure out more easily if there is any assertion error.
> 
> It's really about assertion error messaged displayed to the console - this is the first thing you look for when a test breaks :P

Yeah and it can be confusing when the expected and actual data gets interchanged.

**Comment by suthagar23** [comment]
Thanks @Bisht13

**Pull request merged**
