### PR TITLE
LBAC-15 Added fix to exclude the logged in user session location issue

### PR DESCRIPTION
**Pull request by suthagar23**
# Description 

If the user doesn't contain the location user property, he can still log in through the location selector in the login screen. But the LBAC module failed to identify that user since he hasn't the location information in the user property. So this PR contains the fix for this issue

- If the returned object is the same as the authenticated user, then exclude from restrictions

# Ticket 

Ticket : https://issues.openmrs.org/browse/LBAC-15

### CODE REVIEW

**Comment by dkayiwa** [comment]
Your description is talking about a person not having the location property. But your changes are dealing with this person being the same as the authenticated one. Can you separate these two?

**Comment by suthagar23** [comment]
Separated @dkayiwa . The PR related to Person service can be found here : #29

**Comment by dkayiwa** [comment]
Does this mean that this location restriction does not apply to authenticated users?

**Comment by dkayiwa** [comment]
I do not understand the need for this logic. My understanding has been that location restrictions apply to even authenticated users. Here your code seems to assume otherwise.

**Comment by suthagar23** [comment]
Ohh, the simple use case is below

Let's have a user-A. He assigned to Loc-1 (by location user property). So when he comes to login, it will not show the location selector and the Loc-1 will be assigned as the session location which fetched from the user property. After some where, a module needs the logged in user Full Name, then it will call the getUser(#id-A). So the UserService will return the user-A object. Our LBAC existing implementation will check for location user property, since the session location and location user property is same, it will allow this object.

Let's have another user-B doesn't have assigned location. So he will be redirected to select location through the login and it will be stored only in the session. After some where, a module needs the logged in user Fullname, then it will call the getUser(#id-B). So the UserService will return the user-B object. Our LBAC exiting implementation will check for the location user property. Since this user doesn't have the location user proerty, it will block this object from the view. - Here is the issue which I addressed by this PR.

**Comment by dkayiwa** [comment]
Then this looks like to be safe, our code should only restrict where the location user property is set. Where it is not set, we do not do any filtering.

**Comment by suthagar23** [comment]
Yes, So I have moved this check after the userProperty checking. Let's have a look again. 

So now, if the user doesn't have the userProperty (the `doesUserBelongToGivenLocation` method return false) then only it will check for the authenticated User.

**Comment by dkayiwa** [comment]
If the property is not set, we assume no restrictions for this user.

**Comment by suthagar23** [comment]
Nope, if the property is not set, then no restrictions for this user to get the information only about this user. He can't get any other user information who belongs

**Pull request merged**
