### PR TITLE
Update to 0.2.0-SNAPSHOT version

### PR DESCRIPTION
**Pull request by suthagar23**
# Description

Update to the next development version of the module - 0.2.0-SNAPSHOT

### CODE REVIEW

**Comment by dkayiwa** [comment]
Isn't this supposed to be done automatically by the maven release plugin?

**Comment by suthagar23** [comment]
Yes, I don't know that since it is my first try :smile:

**Comment by dkayiwa** [comment]
was the release done from bamboo?

**Comment by dkayiwa** [comment]
Did you see this? https://github.com/openmrs/openmrs-module-locationbasedaccess/commit/d18ae4db797a6f816d5532a82c2aa0321b8036a4

**Pull request closed without merging**
